services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - db_data:/app/data
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 Mediatheque.wsgi"

volumes:
  db_data:

